version: 2.1

jobs:
  setup:
    docker:
      - image: unknownjustuser/arch:base-devel
    resource_class: large
    working_directory: /tmp/archiso
    steps:
      - checkout:
          path: /tmp/archiso
      - run:
          name: Setup Environment
          command: |
            pacman -Syyu --noconfirm
      - run: ls -al

  build_push_archiso:
    docker:
      - image: unknownjustuser/arch:base-devel
    resource_class: large
    working_directory: /tmp/archiso
    steps:
      - checkout:
          path: /tmp/archiso
      - run:
          name: Build ArchISO
          command: |
            ./build-iso.sh profile iso

workflows:
  build:
    jobs:
      - setup
      - build_push_archiso:
          requires:
            - setup
