name: Build Arch ISO with ArchInstall Commit

on:
  push:
    branches: [ bruh ] # [ master ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archlinux-archiso:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - run: ls -la /home/builder
      - run: pwd
      - run: find .
      - name: builds
        run: |
          cd /home/builder
          sudo -u builder bash -c '
          ./build-iso.sh
          '
      - uses: actions/upload-artifact@v3
        with:
          name: ArchFiery ISO
          path: /home/builder/out/*.iso